parameters:
#    acme_users.example.class: Acme\UsersBundle\Example

services:
#    acme_users.example:
#        class: %acme_users.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
