changepassword:
    pattern:  /
    defaults: { _controller: "AcmeSystemBundle:ChangePassword:edit" }

changepassword_update:
    pattern:  /update
    defaults: { _controller: "AcmeSystemBundle:ChangePassword:update" }
    requirements: { _method: post }
