<?php

namespace Acme\ChildrenBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TextRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChildrenRepository extends EntityRepository
{
	
}
