families:
    pattern:  /
    defaults: { _controller: "AcmeFamilyBundle:Families:index" }

families_show:
    pattern:  /{id}/show
    defaults: { _controller: "AcmeFamilyBundle:Families:show" }

families_new:
    pattern:  /new
    defaults: { _controller: "AcmeFamilyBundle:Families:new" }

families_create:
    pattern:  /create
    defaults: { _controller: "AcmeFamilyBundle:Families:create" }
    requirements: { _method: post }

families_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "AcmeFamilyBundle:Families:edit" }

families_update:
    pattern:  /{id}/update
    defaults: { _controller: "AcmeFamilyBundle:Families:update" }
    requirements: { _method: post }

families_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "AcmeFamilyBundle:Families:delete" }
    requirements: { _method: post }
