parameters:
#    acme_themes.example.class: Acme\ThemesBundle\Example

services:
#    acme_themes.example:
#        class: %acme_themes.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
